### ISSUE TITLE
[Blueprint] Bluey

### ISSUE THREAD

**Issue by iloveteaandcoffee** [TitleCardMaker/Blueprints#832]
### Series Name

Bluey

### Series Year

2018

### Series Database IDs

imdb:tt7678620,tmdb:82728,tvdb:353546

### Creator Username

iloveteaandcoffee, CollinHeist

### Blueprint Description

Tinted Frame card type with the Bluey logo. Font used is from CollinHeist's Bluey Blueprint.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "episode_text_color",
      "frame_color",
      "top_element",
      "bottom_element",
      "logo_size"
    ],
    "extra_values": [
      "#88c0e8",
      "#88c0e8",
      "logo",
      "title",
      "2.0"
    ]
  },
  "fonts": [
    {
      "name": "Bluey",
      "color": "rgb(148,197,245)",
      "file": "Hello Headline Regular.ttf",
      "size": 1.5,
      "title_case": "source"
    }
  ]
}
```

### Preview Title Cards

![Bluey (2018) - S01E01](https://github.com/user-attachments/assets/4b5f4265-afc9-4cfc-b581-148cef21cd3b)

### Zip of Font Files

[fonts.zip](https://github.com/user-attachments/files/16750570/fonts.zip)

**Comment by CollinHeist** [comment]
@iloveteaandcoffee Hey, thanks for submitting this. I don't mind you using the Font from my BP, that's fine 👍🏻 

If you could read the quick instuctions [here](https://titlecardmaker.com/blueprints/#submitting-the-blueprint) and edit your submission, that'd be great (that's why the bot marked this as "Failed"). The .zip that TCM exports has to be separated out - the font file going in the Fonts section, etc.

Let me know if you have any issues

**Comment by CollinHeist** [comment]
I made those changes for you - thanks 👍🏻 /create-blueprint
